[project]
name = "mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nalantishantha", email = "nalantishantha@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastmcp>=2.3.0rc1",
]

[project.scripts]
mcp = "mcp:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
